on:
  push:
    paths:
      - 'conversation/csv/scanning.xlsx' # Triggers only when scanning.xlsx is pushed

jobs:
  check_and_mark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Mark scanning.xlsx as uploaded
        run: |
          mkdir -p conversation/Temp # Ensure directory exists
          # Read existing content, add/update 'scanning_uploaded', write back
          TEMP_FILE="conversation/Temp/upload_temp.txt"
          
          # Read current state if file exists, otherwise start empty
          if [ -f "$TEMP_FILE" ]; then
            CONTENT=$(cat "$TEMP_FILE")
          else
            CONTENT=""
          fi
          
          # Use awk to update or add the 'scanning_uploaded' status
          # If 'scanning_uploaded' exists, update its value. Else, append it.
          if echo "$CONTENT" | grep -q "scanning_uploaded:"; then
            NEW_CONTENT=$(echo "$CONTENT" | awk -v RS="" '{gsub(/scanning_uploaded:[^[:space:]]*/, "scanning_uploaded:true"); print}')
          else
            NEW_CONTENT="${CONTENT}\nscanning_uploaded:true"
          fi
          
          echo -e "$NEW_CONTENT" > "$TEMP_FILE"
          
          echo "Scanning file status marked in $TEMP_FILE"

      - name: Commit upload_temp.txt changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add conversation/Temp/upload_temp.txt
          git commit -m "Marked scanning.xlsx as uploaded" || echo "No changes to commit for scanning.xlsx status."
          git push