# .github/workflows/check_and_initial_merge.yml
name: Check Files and Initial Merge

on:
  push:
    paths:
      - 'conversation/csv/scanning.xlsx'
      - 'conversation/csv/prices.xlsx'

jobs:
  initial_merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Verify both actual data files exist
        id: check_files
        run: |
          SCANNING_FILE="conversation/csv/scanning.xlsx"
          PRICES_FILE="conversation/csv/prices.xlsx"
          
          if [ -f "$SCANNING_FILE" ] && [ -f "$PRICES_FILE" ]; then
            echo "Both scanning.xlsx and prices.xlsx found. Proceeding with initial merge."
            echo "both_files_exist=true" >> "$GITHUB_OUTPUT"
          else
            echo "One or both Excel files missing. Skipping initial merge for now."
            echo "both_files_exist=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Python for Initial Merge
        if: steps.check_files.outputs.both_files_exist == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Required Python Packages for Initial Merge
        if: steps.check_files.outputs.both_files_exist == 'true'
        run: pip install pandas openpyxl

      - name: Run Initial Merge and Create version.txt
        if: steps.check_files.outputs.both_files_exist == 'true'
        run: |
          python3 <<EOF
          import pandas as pd
          import os
          from datetime import datetime
          import sys
          import traceback
          import math # Import math for checking NaN

          try:
              scan_file = "conversation/csv/scanning.xlsx"
              price_file = "conversation/csv/prices.xlsx"
              
              os.makedirs("conversation/Temp", exist_ok=True)
              log_path = "conversation/Logs/workflow_activity.log"

              with open(log_path, "a") as logfile:
                  now = datetime.now().strftime("[%Y-%m-%d %H:%M:%S]")
                  logfile.write(f"{now} Both files received. Starting initial merge.\n")

              scan_df = pd.read_excel(scan_file)
              price_df = pd.read_excel(price_file)

              # Convert OriginalPrice to numeric, coercing errors
              price_df["OriginalPrice"] = pd.to_numeric(price_df["OriginalPrice"], errors='coerce')
              price_df = price_df[["Barcode", "OriginalPrice"]]

              merged_df = pd.merge(scan_df, price_df, on="Barcode", how="left")

              # Apply custom formatting for OriginalPrice
              def format_price(price):
                  if pd.isna(price): # Check for NaN (Not a Number)
                      return '' # Return empty string if NaN/missing
                  elif isinstance(price, (int, float)) and price == int(price):
                      return str(int(price)) # Convert to int then string to remove .0 or .00
                  else:
                      return str(price) # For other cases, return as string

              merged_df["OriginalPrice"] = merged_df["OriginalPrice"].apply(format_price)

              final_columns = ["Barcode", "Article", "Percentage", "OriginalPrice"]
              merged_df = merged_df[final_columns]

              merged_csv_path = "conversation/Temp/merging_temp.csv"
              merged_df.to_csv(merged_csv_path, index=False)

              # Create the version.txt marker file with timestamp
              version_file_path = "conversation/Temp/version.txt"
              timestamp_for_version = datetime.now().strftime("DB_Version_%Y%m%d_%H%M%S")
              with open(version_file_path, 'w') as f:
                  f.write(timestamp_for_version + "\n")
              
              with open(log_path, "a") as logfile:
                  now = datetime.now().strftime("[%Y-%m-%d %H:%M:%S]")
                  logfile.write(f"{now} Merging complete. {os.path.basename(merged_csv_path)} created. Version marker file ({os.path.basename(version_file_path)}) created with content: {timestamp_for_version}.\n")

          except Exception as e:
              log_path_error = "conversation/Logs/workflow_activity.log"
              with open(log_path_error, "a") as logfile:
                  now = datetime.now().strftime("[%Y-%m-%d %H:%M:%S]")
                  logfile.write(f"{now} ERROR: Initial Merge Failed: {str(e)}\n")
                  logfile.write(traceback.format_exc())
              sys.exit(1) # Fail the job if initial merge fails
          EOF
        env:
          PYTHONUNBUFFERED: 1

      - name: Commit merged_temp.csv and version.txt
        if: steps.check_files.outputs.both_files_exist == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add conversation/Temp/merging_temp.csv
          git add conversation/Temp/version.txt
          git add conversation/Logs/workflow_activity.log # Also commit log updates
          git commit -m "Initial Merge: Created merging_temp.csv and version.txt." || echo "No new changes to commit."
          git push
