# .github/workflows/check_scanning_file.yml
name: Check Scanning File Upload

on:
  push:
    paths:
      - 'conversation/csv/scanning.xlsx' # Triggers only when scanning.xlsx is pushed

jobs:
  check_and_mark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Mark scanning.xlsx as uploaded using Python
        run: |
          python3 <<EOF
          import os
          from datetime import datetime

          temp_file_path = "conversation/Temp/upload_temp.txt"
          
          # Ensure directory exists
          os.makedirs(os.path.dirname(temp_file_path), exist_ok=True)

          # Read existing statuses
          statuses = {}
          if os.path.exists(temp_file_path):
              with open(temp_file_path, 'r') as f:
                  for line in f:
                      line = line.strip()
                      if line and ':' in line:
                          key, value = line.split(':', 1)
                          statuses[key.strip()] = value.strip()
          
          # Update scanning_uploaded status with timestamp
          timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
          statuses['scanning_uploaded'] = f"true_{timestamp}"

          # Write updated statuses back to file, ensuring a clean format
          with open(temp_file_path, 'w') as f:
              for key, value in sorted(statuses.items()): # Sort for consistent order
                  f.write(f"{key}:{value}\n")
          
          print(f"Scanning file status marked in {temp_file_path} with timestamp.")
          EOF

      - name: Commit upload_temp.txt changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add conversation/Temp/upload_temp.txt
          git commit -m "Marked scanning.xlsx as uploaded with timestamp via Python." || echo "No changes to commit for scanning.xlsx status."
          git push
