# .github/workflows/check_prices_file.yml
name: Check Prices File Upload

on:
  push:
    paths:
      - 'conversation/csv/prices.xlsx' # Triggers only when prices.xlsx is pushed

jobs:
  check_and_mark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Mark prices.xlsx as uploaded
        run: |
          mkdir -p conversation/Temp # Ensure directory exists
          TEMP_FILE="conversation/Temp/upload_temp.txt"
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S") # Get current timestamp

          # Read existing content, update or add 'prices_uploaded' with timestamp
          if [ -f "$TEMP_FILE" ]; then
            CONTENT=$(cat "$TEMP_FILE")
          else
            CONTENT=""
          fi
          
          # Remove any existing prices_uploaded line to avoid duplicates
          CLEANED_CONTENT=$(echo "$CONTENT" | grep -v "prices_uploaded:")
          
          # Add the new prices_uploaded line with timestamp
          NEW_CONTENT="${CLEANED_CONTENT}\nprices_uploaded:true_${TIMESTAMP}"
          
          # Remove leading/trailing newlines and write to file
          echo -e "$NEW_CONTENT" | sed '/^$/d' > "$TEMP_FILE"
          
          echo "Prices file status marked in $TEMP_FILE with timestamp."

      - name: Commit upload_temp.txt changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add conversation/Temp/upload_temp.txt
          git commit -m "Marked prices.xlsx as uploaded with timestamp." || echo "No changes to commit for prices.xlsx status."
          git push
