# .github/workflows/create_scanning_marker.yml
name: Create Scanning Upload Marker

on:
  push:
    paths:
      - 'conversation/csv/scanning.xlsx' # Triggers only when scanning.xlsx is pushed

jobs:
  create_marker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create scanning_uploaded.txt marker
        run: |
          mkdir -p conversation/Temp # Ensure directory exists
          touch conversation/Temp/scanning_uploaded.txt # Create an empty marker file
          echo "Scanning file marker created at $(date)" > conversation/Temp/scanning_uploaded.txt # Add content (optional, but good for debugging)
          echo "Created scanning_uploaded.txt"

      - name: Commit scanning_uploaded.txt
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add conversation/Temp/scanning_uploaded.txt
          git commit -m "Created scanning_uploaded.txt marker" || echo "No changes to commit (marker already exists or pushed)."
          git push