# .github/workflows/create_prices_marker.yml
name: Create Prices Upload Marker

on:
  push:
    paths:
      - 'conversation/csv/prices.xlsx' # Triggers only when prices.xlsx is pushed

jobs:
  create_marker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create prices_uploaded.txt marker
        run: |
          mkdir -p conversation/Temp # Ensure directory exists
          touch conversation/Temp/prices_uploaded.txt # Create an empty marker file
          echo "Prices file marker created at $(date)" > conversation/Temp/prices_uploaded.txt # Add content (optional, but good for debugging)
          echo "Created prices_uploaded.txt"

      - name: Commit prices_uploaded.txt
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add conversation/Temp/prices_uploaded.txt
          git commit -m "Created prices_uploaded.txt marker" || echo "No changes to commit (marker already exists or pushed)."
          git push