name: CSV to Lightweight SQLite Converter with Version Table

on:
  push:
    paths:
      - 'conversation/csv/*.csv'

jobs:
  convert_csv_to_sqlite:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Tools
        run: pip install pandas sqlite-utils

      - name: Find Latest CSV File
        id: findfile
        run: |
          latest_file=$(ls -t conversation/csv/*.csv | head -1)
          echo "file=$latest_file" >> $GITHUB_OUTPUT

      - name: Convert CSV to SQLite with Version Table (Optimized)
        run: |
          csv_file="${{ steps.findfile.outputs.file }}"
          db_name=$(basename "$csv_file" .csv).db

          # Step 1: Create empty DB first
          sqlite3 "$db_name" 'PRAGMA journal_mode=OFF; PRAGMA synchronous=OFF;'

          # Step 2: Insert CSV Data into 'sc'
          sqlite-utils insert "$db_name" sc "$csv_file" --csv --detect-types

          # Step 3: Insert databaseversion table
          version_name=$(basename "$csv_file")
          echo "DBversion" > version.csv
          echo "$version_name" >> version.csv
          sqlite-utils insert "$db_name" databaseversion version.csv --csv

          # Step 4: Shrink DB size
          sqlite3 "$db_name" 'VACUUM;'

          mkdir -p conversation/Ready
          mv "$db_name" conversation/Ready/

      - name: Commit Lightweight SQLite DB
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add conversation/Ready/*.db
          git commit -m "Added optimized SQLite DB"
          git push
