# .github/workflows/on_prices_upload.yml
name: On Prices File Upload - Check & Dispatch Main

on:
  push:
    paths:
      - 'conversation/csv/prices.xlsx' # Triggers only when prices.xlsx is pushed

jobs:
  check_and_dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Log Entry for Prices Upload Check
        run: |
          mkdir -p conversation/Logs # Ensure Logs directory exists
          echo "$(date +"%Y-%m-%d %H:%M:%S") - Prices.xlsx uploaded. Checking for scanning.xlsx for main workflow dispatch." >> conversation/Logs/workflow_activity.log
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add conversation/Logs/workflow_activity.log
          git commit -m "Log: Prices.xlsx upload detected." || echo "No new log entry commit."
          git push || echo "Log push failed, might be merged by another push."

      - name: Check if both files exist and Dispatch Main Workflow
        run: |
          SCANNING_FILE="conversation/csv/scanning.xlsx"
          PRICES_FILE="conversation/csv/prices.xlsx"
          
          echo "Checking if both actual data files exist in the repository..."
          
          if [ -f "$SCANNING_FILE" ] && [ -f "$PRICES_FILE" ]; then
            echo "Both scanning.xlsx and prices.xlsx found. Dispatching main conversion workflow."
            
            # Dispatch the main_conversion_workflow.yml using GitHub CLI
            # GITHUB_TOKEN is a default token provided by GitHub Actions, no manual setup needed.
            gh workflow run main_conversion_workflow.yml --ref ${{ github.ref }} || { echo "Failed to dispatch main workflow!"; exit 1; }
            echo "Main conversion workflow dispatched successfully."
          else
            echo "Only prices.xlsx (or neither) found. Not dispatching main workflow yet."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This uses the default GitHub-provided token
