# .github/workflows/phase2_finalize_db_with_version.yml
name: Phase 2 - Finalize SQLite ZIP with Version

on:
  push:
    paths:
      - 'conversation/Temp/version.txt' # This workflow triggers ONLY on version.txt push

jobs:
  finalize_db_with_version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Required Python Packages
        run: pip install sqlite-utils

      - name: Rename Temp DB, Zip It, Update Logs
        run: |
          python3 <<EOF
          import sqlite3
          import zipfile
          import os
          from datetime import datetime
          import traceback

          try:
              version_path = "conversation/Temp/version.txt"
              db_source = "conversation/Temp/temp.db"
              log_path = "conversation/Temp/conversion_log.txt" # Log file is expected from Phase 1

              # Check if necessary files exist
              if not os.path.exists(version_path):
                  raise FileNotFoundError(f"Error: version.txt not found at {version_path}. Please upload version.txt to trigger finalization.")
              if not os.path.exists(db_source):
                  raise FileNotFoundError(f"Error: temp.db not found at {db_source}. Phase 1 must complete successfully first.")
              # Log file is optional here, it might not exist if phase 1 ran much earlier and was pruned
              # if not os.path.exists(log_path):
              #     # Create if it doesn't exist to log errors
              #     os.makedirs(os.path.dirname(log_path), exist_ok=True)
              #     with open(log_path, "w") as f:
              #         f.write(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Phase 2: Log started (temp.db or version.txt might have been missing originally).\n")

              with open(version_path, "r") as vfile:
                  version_name = vfile.read().strip() # Read the version from the file

              # Ensure the target directory for the final DB exists
              os.makedirs("conversation/Ready", exist_ok=True)
              db_target = f"conversation/Ready/{version_name}.db" # Final DB name based on version.txt

              # Rename/Move the temp DB to its final location and name
              os.rename(db_source, db_target)

              # Update the databaseversion table in the *newly renamed* database
              with sqlite3.connect(db_target) as conn:
                  conn.execute("CREATE TABLE IF NOT EXISTS databaseversion (DBversion TEXT)")
                  conn.execute("DELETE FROM databaseversion") # Clear any existing version entries
                  conn.execute("INSERT INTO databaseversion (DBversion) VALUES (?)", (version_name,)) # Insert version from version.txt
                  conn.commit()
                  conn.execute("VACUUM;")

              zip_name = f"conversation/Ready/{version_name}.zip" # Zip name based on version.txt
              with zipfile.ZipFile(zip_name, 'w', zipfile.ZIP_DEFLATED) as zipf:
                  # Write the db_target file into the zip, but store it as its basename (e.g., "myversion.db" inside the zip)
                  zipf.write(db_target, os.path.basename(db_target))

              # Append to the existing log file
              with open(log_path, "a") as logfile:
                  now = datetime.now().strftime("[%Y-%m-%d %H:%M:%S]")
                  logfile.write(f"{now} Phase 2: Finalizing with version: {version_name}\n")
                  logfile.write(f"{now} Phase 2: Finalized DB: {db_target}, Zipped to: {zip_name}\n")
                  logfile.write(f"{now} Phase 2: Conversion Complete\n")

          except Exception as e:
              # Ensure log directory exists for error logging
              os.makedirs("conversation/Temp", exist_ok=True)
              log_path_error = "conversation/Temp/conversion_log.txt"
              with open(log_path_error, "a") as logfile:
                  now = datetime.now().strftime("[%Y-%m-%d %H:%M:%S]")
                  logfile.write(f"{now} Phase 2: Error occurred during finalization: {str(e)}\n")
                  logfile.write(traceback.format_exc()) # Write full traceback for better debugging
              raise # Re-raise the exception so the GitHub Action fails
          EOF

      - name: Commit Finalized Files and Clean Up Temp
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          
          # Add the newly created finalized DB and ZIP file
          git add conversation/Ready/*.db conversation/Ready/*.zip
          # Add the updated log file and the version.txt which was part of the trigger
          git add conversation/Temp/conversion_log.txt conversation/Temp/version.txt
          
          # Remove the temporary DB file from the repository
          git rm conversation/Temp/temp.db || true # || true prevents error if file doesn't exist for some reason
          
          git commit -m "Phase 2: Finalized SQLite with version from version.txt"
          git push
